workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'

include:
  - template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml
  - template: Jobs/SAST.latest.gitlab-ci.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]

stages:
 - prepare
 - lint
 - test
 - publish

.prepare-image:
  image: docker:latest
  stage: prepare
  interruptible: true
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$IMAGE || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:$IMAGE -t $CI_REGISTRY_IMAGE:$IMAGE -f ./docker_images/$IMAGE.dockerfile .
    - echo $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE:$IMAGE
  rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        changes:
          - docker_images/*

prepare:python3.8:
  extends: .prepare-image
  variables:
    IMAGE: python3.8

prepare:python3.9:
  extends: .prepare-image
  variables:
    IMAGE: python3.9

prepare:python3.10:
  extends: .prepare-image
  variables:
    IMAGE: python3.10

lint:python3:
  image: $CI_REGISTRY_IMAGE:python3.8
  stage: lint
  script:
    - tox -e flake8

test:pages:
  image: python:3.9
  stage: test
  needs: []  # We can execute this out-of-order
  before_script:
  - pip install mkdocs>=1.1.2
  script:
  - mkdir -p test
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  except:
  - master

test:python3.8:django2.2:
 image: $CI_REGISTRY_IMAGE:python3.8
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py38-dj22

test:python3.8:django3.2:
 image: $CI_REGISTRY_IMAGE:python3.8
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py38-dj32

test:python3.8:django4.1:
 image: $CI_REGISTRY_IMAGE:python3.8
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py38-dj41

test:python3.9:django2.2:
 image: $CI_REGISTRY_IMAGE:python3.9
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py39-dj22

test:python3.9:django3.2:
 image: $CI_REGISTRY_IMAGE:python3.9
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py39-dj32

test:python3.9:django4.1:
 image: $CI_REGISTRY_IMAGE:python3.9
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py39-dj41

test:python3.10:django3.0:
 image: $CI_REGISTRY_IMAGE:python3.10
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py310-dj30

test:python3.10:django3.1:
 image: $CI_REGISTRY_IMAGE:python3.10
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py310-dj31

test:python3.10:django3.2:
 image: $CI_REGISTRY_IMAGE:python3.10
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py310-dj32

test:python3.10:django4.1:
 image: $CI_REGISTRY_IMAGE:python3.10
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py310-dj41

build and publish:
  stage: publish
  image: python:3.8
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
  before_script:
    - pip install twine setuptools wheel
    - rm -rf dist
    - python setup.py sdist bdist_wheel
  script:
    - python -m twine upload --username=__token__ --password=$PROD_PYPI_TOKEN --repository-url https://upload.pypi.org/legacy/ dist/*

pages:
  image: python:3.9
  stage: publish
  needs: []
  before_script:
  - pip install mkdocs>=1.1.2
  script:
  - mkdir -p public
  - mkdocs build --strict --verbose
  artifacts:
    paths:
    - public
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
