stages:
 - prepare
 - lint
 - test

prepare:python3.8:
  stage: prepare
  image: docker:latest
  services:
    - docker:dind
  variables:
    GIT_STRATEGY: none  # Prevent cloning
    DOCKERFILE: >- # Generate a Dockerfile for the build image
      FROM python:3.8\n
      SHELL ["/bin/bash", "-c"]\n
      RUN apt-get update\n
      RUN apt-get install -y default-jre\n
      RUN pip install tox\n
      RUN gcloud version || true\n
      RUN if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi\n
      RUN source /root/google-cloud-sdk/path.bash.inc && gcloud version\n
      RUN CLOUDSDK_CORE_DISABLE_PROMPTS=1 source /root/google-cloud-sdk/path.bash.inc && gcloud components install cloud-datastore-emulator beta\n
  before_script:  # Put the variable into a Dockerfile
     - echo -e $DOCKERFILE > Dockerfile
     - cat Dockerfile
  script:
     - docker pull $CI_REGISTRY_IMAGE:python3.8 || true
     - docker build --cache-from $CI_REGISTRY_IMAGE:python3.8 -t $CI_REGISTRY_IMAGE:python3.8 .
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
     - docker push $CI_REGISTRY_IMAGE:python3.8

lint:python3:
  image: $CI_REGISTRY_IMAGE:python3.8
  stage: lint
  script:
    - tox -e flake8

test:python3.8:django2.2:
 image: $CI_REGISTRY_IMAGE:python3.8
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py38-22

test:python3.8:django3.0:
 image: $CI_REGISTRY_IMAGE:python3.8
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py38-30

test:python3.8:django3.1:
 image: $CI_REGISTRY_IMAGE:python3.8
 stage: test
 before_script:
   - source /root/google-cloud-sdk/path.bash.inc
 script:
   - tox -e py38-30
