site_name: Djangae Documentation
site_url: https://potato-oss.gitlab.io/djangae/djangae/
site_dir: public
repo_url: https://gitlab.com/potato-oss/djangae/djangae
nav:
- Home: index.md
- Installation & Deployment: installation.md
- Local/remote management commands: sandbox.md
- Environment: environment.md
- Utils: utils.md
- Storage backends: storage.md
- Background Processing: deferred.md
- Contrib apps:
  - Googleauth: contrib_googleauth.md
  - Search: contrib_search.md
  - Pagination: contrib_pagination.md
  - Scheduled backups: contrib_backup.md
  - Security: contrib_security.md
  - Thread locking: contrib_locking.md
- Cloud Run: cloud_run.md
- Contributing & Testing: contributing.md
- Commercial Support: commercial_support.md
- Work with us!: work_with_potato.md
theme: readthedocs
